spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:import/dev.properties
  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 3
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

springdoc:
  packages-to-scan: demo.kotlinboilerplate
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  model-and-view-allowed: true
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true
    path: /docs
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: asc
    display-request-duration: true
    url: /docs
    disable-swagger-default-url: true
    persist-authorization: true
