spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:import/prod.properties
  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 3
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
