server:
  servlet:
    context-path: "/api/v1"
    encoding:
      force: true
      charset: utf-8

spring:
  application:
    name: kotlin-boiler-plate
  #  profiles:
  #    active: local
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: true
