server:
  servlet:
    context-path: "/api/v1"
    encoding:
      force: true
      charset: utf-8

spring:
  application:
    name: kotlin-sample
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace